import type { GalleryImage } from "@/content/types";

export const galleryImages: GalleryImage[] = [
  { src: "/gallery/Crowd.jpg", alt: "AbilityX 1.0 audience gathered during a session." },
  { src: "/gallery/stage.jpg", alt: "The AbilityX 1.0 stage and screen during the conference." },
  { src: "/gallery/Panel.jpg", alt: "A panel discussion during AbilityX 1.0." },
  { src: "/gallery/Networking.jpg", alt: "Attendees networking at AbilityX 1.0." },
  { src: "/gallery/Exhibition-floor.jpg", alt: "AbilityX 1.0 exhibition floor activity." },
  { src: "/gallery/Speaker-moment.jpg", alt: "A featured speaker moment from AbilityX 1.0." },
  { src: "/abilityx/Extra Pictures/AbilityX-4.jpg", alt: "AbilityX 1.0 gallery photo 4." },
  { src: "/abilityx/Extra Pictures/AbilityX-41 (1).jpg", alt: "AbilityX 1.0 gallery photo 41." },
  { src: "/abilityx/Extra Pictures/AbilityX-55.jpg", alt: "AbilityX 1.0 gallery photo 55." },
  { src: "/abilityx/Extra Pictures/AbilityX-64 (1).jpg", alt: "AbilityX 1.0 gallery photo 64." },
  { src: "/abilityx/Extra Pictures/AbilityX-124.jpg", alt: "AbilityX 1.0 gallery photo 124." },
  { src: "/abilityx/Extra Pictures/AbilityX-267.jpg", alt: "AbilityX 1.0 gallery photo 267." },
  { src: "/abilityx/Extra Pictures/AbilityX-283.jpg", alt: "Conference attendees in conversation at AbilityX 1.0." },
  { src: "/abilityx/Extra Pictures/AbilityX-301.jpg", alt: "A documentary-style event photograph from AbilityX 1.0." },
  { src: "/abilityx/Extra Pictures/AbilityX-302.jpg", alt: "AbilityX 1.0 gallery photo 302." },
  { src: "/abilityx/Extra Pictures/AbilityX-393.jpg", alt: "Audience engagement during an AbilityX 1.0 session." },
  { src: "/abilityx/Extra Pictures/AbilityX-435.jpg", alt: "AbilityX 1.0 gallery photo 435." },
  { src: "/abilityx/Extra Pictures/AbilityX-448.jpg", alt: "AbilityX 1.0 gallery photo 448." },
  { src: "/abilityx/Extra Pictures/AbilityX-449.jpg", alt: "AbilityX 1.0 gallery photo 449." },
  { src: "/abilityx/Extra Pictures/AbilityX-456.jpg", alt: "AbilityX 1.0 gallery photo 456." },
  { src: "/abilityx/Extra Pictures/AbilityX-457.jpg", alt: "AbilityX 1.0 gallery photo 457." },
  { src: "/abilityx/Extra Pictures/AbilityX-465.jpg", alt: "AbilityX 1.0 gallery photo 465." },
  { src: "/abilityx/Extra Pictures/AbilityX-497.jpg", alt: "AbilityX 1.0 gallery photo 497." },
  { src: "/abilityx/Extra Pictures/AbilityX-507.jpg", alt: "Closing event energy captured at AbilityX 1.0." },
];
